// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// PostController is an autogenerated mock type for the PostController type
type PostController struct {
	mock.Mock
}

// AddPost provides a mock function with given fields: resp, req
func (_m *PostController) AddPost(resp http.ResponseWriter, req *http.Request) {
	_m.Called(resp, req)
}

// GetPosts provides a mock function with given fields: resp, req
func (_m *PostController) GetPosts(resp http.ResponseWriter, req *http.Request) {
	_m.Called(resp, req)
}

// NewPostController creates a new instance of PostController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostController(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostController {
	mock := &PostController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
