// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Router is an autogenerated mock type for the Router type
type Router struct {
	mock.Mock
}

// GET provides a mock function with given fields: uri, f
func (_m *Router) GET(uri string, f func(http.ResponseWriter, *http.Request)) {
	_m.Called(uri, f)
}

// POST provides a mock function with given fields: uri, f
func (_m *Router) POST(uri string, f func(http.ResponseWriter, *http.Request)) {
	_m.Called(uri, f)
}

// SERVE provides a mock function with given fields: port
func (_m *Router) SERVE(port string) {
	_m.Called(port)
}

// NewRouter creates a new instance of Router. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Router {
	mock := &Router{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
